### ISSUE TITLE
Compiling `cpp2v` on Ubuntu / path to llvm-config

### ISSUE THREAD

**Issue by co-dan** [bedrocksystems/cpp2v#109]
I've installed the packages `clang-7` and `libclang-7-dev` as mentioned in the readme. However, for the cmake file I had to additionally install the packages `llvm-7` and `llvm-7-dev`, which provide the `llvm-config` program used in `cmake/modules/FindLLVM.cmake`.

Furthermore, I had to edit this cmake module to change `llvm-config` to `llvm-config-7` (because that's the name of the executable provided by the `llvm-7` package on my system).

**Comment by gmalecha** [comment]
Thanks, @co-dan! I will update the README!

**Comment by gmalecha** [comment]
This should be fixed now.
