### ISSUE TITLE
Avoid overeager unification in `work`

### ISSUE THREAD

**Issue by jmgrosen** [bedrocksystems/cpp2v#141]
Right now `work` sometimes unifies existentials to bad values that make the goal unprovable. This can sometimes be worked around but is annoying. Ideally we'd just prevent unification unless we can solve the goal, but another solution might be to have another tactic that doesn't introduce evars for exists quantifiers so that the user can handle it more manually.

**Comment by gmalecha** [comment]
This is especially bad with the atomic instructions which have higher-order predicates, which results in entailments such as `... |- ?X ** ...`. Even `perm_right` gets stuck on this.

**Comment by jmgrosen** [comment]
The issue I thought I was seeing yesterday was actually user error :) So I don't know of any more cases of this.

**Comment by gmalecha** [comment]
Closing this, pending additional problems.
