### ISSUE TITLE
Try to keep names

### ISSUE THREAD

**Issue by jmgrosen** [bedrocksystems/cpp2v#142]
Right now `work` seems to pretty much clobber names when intro-ing from existential quantifiers. It would be nice if it tried to keep them.

**Comment by jmgrosen** [comment]
Also try to have more type-specific names. Right now I have `x : val, x0 : region, x1 : mpred` all in my context and it's confusing, especially for a newcomer.

**Comment by jmgrosen** [comment]
It would also be nice if names of C++ variables also influenced their Coq values' names, but it doesn't seem to be possible to use Gallina strings with `fresh`, so this might require a plugin.

**Comment by gmalecha** [comment]
This should be pretty easy to accomplish with a plugin.

**Comment by gmalecha** [comment]
This seems to be mostly addressed with the recent changes to the automation. I'm going to close and we can re-open specific issues if we find them.
