### ISSUE TITLE
Make build work on Travis

### ISSUE THREAD

**Issue by jmgrosen** [bedrocksystems/cpp2v#152]
CI is pretty helpful. We probably don't want to spend time on it this week, but maybe soon after that.

Apparently right now the blocker is installing llvm-8 etc. on Travis.

**Comment by gmalecha** [comment]
There is a pull request for this.

**Comment by jmgrosen** [comment]
Ah, so there is!

**Comment by gmalecha** [comment]
There is a PR, but not an issue. We can track #91 in this.

**Comment by gmalecha** [comment]
Closed by #91
